name: Backend Container Deployment

on:
  push:
    branches: [main]
    paths: ["backend/src/**"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ›« Checkout the branch inside Agent Runner environment
        uses: actions/checkout@v2

      - name: ğŸ”’ Login to Azure
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.CONTAINERBACKEND_AZURE_CREDENTIALS }}

      - name: ğŸ—ï¸ Push container image to Azure Container Registry + Update existing container
        uses: Azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }}/backend/src
          registryUrl: arolariu.azurecr.io
          registryUsername: ${{ secrets.CONTAINERBACKEND_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERBACKEND_REGISTRY_PASSWORD }}
          containerAppName: container-backend
          resourceGroup: arolariu-rg
          imageToBuild: arolariu.azurecr.io/container-backend:latest
          dockerfilePath: Dockerfile
